---
title: "A Proposal to Improve NCB Communication Tools"
author: "Max Kuhn"
---

## Unmet Need

The Nonclinical Biostatistics website is difficult to update and maintain. 

## Proposal

I propose that the tools to use for NCB communication be simpler, modern, and functional. I suggest using Quarto^[Quarto is an open-source scientific and technical publishing system. It is free. Quarto uses a markdown-based system to create content. It was used to create and publish this proposal. See the code to make this document here.] and GitHub^[GitHub is a proprietary developer platform (owned by Microsoft) that allows developers to create, store, manage, and share their projects. For NCB, it would help us collaborate and publish our content.] as the primary mechanisms to achieve this. 

The goal is to improve tooling; I’m not suggesting any change in roles or personnel within NCB. 

Specifics: 

- Acquire URLs for a main site and, optionally, a site for the biennial NCB conference. `ncbiostats.org` is open ($10/y) as is `ncb-conf.org` ($10/y).
- Create an `ncbiostats` GitHub [organization](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/about-organizations) (free)
- Have volunteers create the initial NCB website. 
- Extensively document how the site functions, along with templates for common tasks (e.g., news items).
- Deploy site preview for review and comments.
- Deploy and communicate the new site.
- Forward the current ASA site to the new independent site. 

After getting the current site’s files, I believe a new site draft would take 1-2 weeks, and documentation would take 1-2 months. 

### Benefits {.unnumbered}

- The site will be easier to maintain and update. 
- A modern web framework is used to provide security and accessibility. 
- Requires a low technical barrier with no coding. 
- GitHub enables users/contributors to collaborate easily and efficiently.  
- Previous content can be migrated without much trouble, 
- Improved SEO to help attract more visitors. 
- URLs are easy to remember and access. 

### Drawbacks {.unnumbered}

- Additional yearly cost is $20. 
- Something new to learn. 
- For accessibility, we’d need light and dark mode versions of logos and images. 

## Open questions

We can easily deploy the site(s) to custom URLs via GitHub. Another option is [Netlify](https://www.netlify.com/), which can provide deployment previews to test/review the published site before “going live.” We can get a free Netlify account for nonprofits/open-source projects. I would probably just use GitHub to avoid another dependency. If we think deployment previews are worth it, we can discuss Netlify. 

The ASA may have a graphic designer who might improve aesthetics (if needed). 
